version: '3.3'

services:
  postgres-server:
    container_name: postgres-server
    image: postgres:14
    restart: always
    environment:  
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data
    volumes: 
      - /storage/postgres/:/var/lib/postgresql/data:rw

  zabbix-server:
    container_name: zabbix-server
    hostname: zabbix_server  
    image: zabbix/zabbix-server-pgsql:latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:
      - /storage/zabbix/:/usr/lib/zabbix/alertscripts:rw

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    ports:
      - '80:8080'
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Sao_Paulo"  
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:latest
    privileged: true
    restart: always
    ports:
      - '10050:10050'  
    environment:
      - ZBX_SERVER_HOST=172.21.0.2

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource  
    depends_on:
      - postgres-server
      - zabbix-server
    volumes:
      - /storage/grafana:/etc/grafana/provisioning/data
      - /storage/grafana:/var/lib/grafana    
